### ISSUE TITLE
Canvas is not displayed on screen

### ISSUE THREAD

**Issue by nidhinkumar06** [actions-on-google/dialogflow-interactive-canvas-nodejs#1]
I have tried the interactive-canvas as per the instructions given but i couldn't see the canvas getting  displayed on the test screen nor in my phone.

Things i have checked:

1. Node Version - 10.15.1
2. Installed the plugins
3. Hosted html files and cloud functions as per the instructions
4. Enabled Immersive Canvas
5. Added webhook url
6. Changed actions-on-google plugin to developer preview

But when i run the hosted site there i could see the image with animation as below
![imageanimation](https://user-images.githubusercontent.com/10459220/57581149-2dfc3100-74d1-11e9-90e0-8a459330858f.png)

When i try to run the action in simulator i couldn't see anything like below
![game](https://user-images.githubusercontent.com/10459220/57581154-48cea580-74d1-11e9-8579-24f63e0e91bc.png)

**Comment by Canain** [comment]
Hi, from your screenshot, it seems that the `agent.zip` is not completely imported into the Dialogflow project. When said `Talk to my test app`, it responded with `Good day! What can I do for you today?` which is one of the default response whereas it should be `Welcome! Do you want me to change color or pause spinning? You can also tell me to ask you later.` for this sample.

Can you double check you did [step 4 under **Actions Console**](https://github.com/actions-on-google/dialogflow-interactive-canvas-nodejs#actions-console) in the README correctly?

**Comment by nidhinkumar06** [comment]
@Canain Your are right. Instead of **Restore** from .zip, I have selected **Import** from .zip that causes the problem. Now it's working as expected. Thank you.
