### ISSUE TITLE
onUpdate is not calling

### ISSUE THREAD

**Issue by ravirupareliya** [actions-on-google/dialogflow-interactive-canvas-nodejs#4]
I have deployed it on firebase hosting. While testing it with actions simulator, it is calling conversation but does not call onUpdate callback of ImmersiveResponse.

     conv.ask(`Ok, I changed my color to ${color}. What else?`);
     conv.ask(new ImmersiveResponse({
         state: {
             tint: tints[color],
         },
     }));

from above code I am able to see response `Ok, I changed my color to Red. What else?` but onUpdate log is not printed on firebase functions console.

code snippet for callback

    // register assistant canvas callbacks
    const callbacks = {
        onUpdate(state) {
            console.log('onUpdate', JSON.stringify(state));
            if ('tint' in state) {
                sprite.tint = state.tint;
            }
      },
    };
    assistantCanvas.ready(callbacks);

**Comment by Fleker** [comment]
onUpdate would not be called in your Firebase Function at all. It would appear locally in your web surface and be logged in your local devtools.
