### ISSUE TITLE
Tests on mobile phones show this device is not supported.

### ISSUE THREAD

**Issue by YinXiuYu** [actions-on-google/dialogflow-interactive-canvas-nodejs#6]
I tested it on the simulator, but on the phone it isn't supported.

**Comment by LeonNicholls** [comment]
Interactive Canvas is currently only supported on Android phones. Also ensure that your Google app is up to date.

**Comment by YinXiuYu** [comment]
Hi , entertailion,
Thanks for your reply, I have updated the Google app to the latest ,but it still doesn't work.
Looking forward to your reply, thanks a lot in advance!

**Comment by LeonNicholls** [comment]
Which Android device are you using and what version of Android?
Also, what exactly happens when you are running the Action on your phone?
Are you using the same user account on the phone as in the simulator?

**Comment by YinXiuYu** [comment]
I use the Pixel 3XL with the android 10 version, I used the same user account to test in the simulator and     on my Pixel 3 XL device, it worked in the simulator, but displayed  "my test app isn't supported on this device" on my Pixel 3 XL.

**Comment by LeonNicholls** [comment]
Can you please file a support issue and provide your project ID: https://developers.google.com/assistant/support
